# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [1]:
def share_bread(N, K):
    x = K // N
    y = K % N
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [2]:
def leap_year(year):
    if year % 4 == 0 and year % 100 != 0:
        text_result = 'YOU SHALL PASS'
    elif year % 400 == 0:
        text_result = 'YOU SHALL PASS'
    else:
        text_result = 'YOU SHALL NOT PASS'
             
    return text_result

assert leap_year(5) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [3]:
import math

def amulet_area(a, b, c):
    p = (a + b + c) / 2
    S = math.sqrt(p * (p - a) * (p - b) * (p - c))
    return S

assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [4]:
import math
from scipy import spatial

def cal_euclidean(a, b):    
    distance = math.sqrt(sum(pow((a - b),2) for a, b in zip(a, b)))
    return distance

def cal_manhattan(a, b):    
    distance = math.sqrt(sum(abs((a - b)) for a, b in zip(a, b)))
    return distance

def cal_cosine(a, b):    
    distance = 1 - spatial.distance.cosine(a,b)
    return distance

In [5]:
import numpy as np

a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

31.12876483254676
9.1104335791443
-0.7782927287480772


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [12]:
import numpy as np
   
    
#my_array = [0, 1]

#1 option
#for x in range(100 - len(my_array)):
#    x = np.random.uniform(0, 1)
#    my_array.append(x)

#2 option
#x = [np.random.uniform(0, 1) for _ in range(100 - len(my_array))]
#my_array.extend(x)

#3 option 
my_array = np.random.rand(100)
index_min = np.argmin(my_array)
index_max = np.argmax(my_array)
my_array[index_min] = 0
my_array[index_max] = 1



print(f"\033[1mIn the random array\033[0m: \n{my_array}\n\033[1mof len {len(my_array)}\nthe maximum number is {int(np.max(my_array))} and the minimum number is {int(np.min(my_array))}.")



In the random array: 
[0.00758876 0.03163443 0.0332488  0.20379865 0.         0.39781472
 0.92207373 0.98046527 0.68948313 0.59172142 0.36330118 0.11455588
 0.46916445 0.05944197 0.18773991 0.31742123 0.67423028 0.6435353
 0.38867696 0.23244452 0.68063091 0.38415676 0.9117463  0.89514595
 0.39561875 0.38556344 0.31331305 0.29827921 0.51926353 0.26462742
 0.0912974  0.43927882 0.14245314 0.8788574  0.90248699 0.4507918
 1.         0.03431094 0.60027001 0.9688838  0.25816609 0.12835035
 0.62835169 0.12181683 0.53028222 0.27206416 0.81323961 0.91482823
 0.27670665 0.69828898 0.62809554 0.79826017 0.0918756  0.93283171
 0.78683018 0.76236251 0.01626456 0.39031035 0.05419458 0.31820778
 0.47115253 0.79767765 0.82695556 0.42842584 0.51250456 0.73032641
 0.04091857 0.75274794 0.73231767 0.18900097 0.49730987 0.95641134
 0.61445885 0.69261086 0.20777568 0.07413868 0.0412853  0.03511947
 0.34907204 0.10424977 0.96305126 0.63572888 0.68056767 0.67852496
 0.26518258 0.78526151 0.20430111 0.495451

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [302]:
import numpy as np


#1 option
#my_array = np.array([[np.random.randint(0, 50) for x in range(6)] for y in range(5)])
#index = np.argmax(my_array)
   
#if index in range(0,6):
#    limit = index
#if index in range(6,12):
#    limit = index-6
#if index in range(12,18):
#    limit = index-12
#if index in range(18,24):
#    limit = index-18
#if index in range(24,30):
#    limit = index-24
#selected_column = my_array[:, limit]

#print('Shape: ',my_array.shape)
#print(f"\033[1m{my_array}\033[0m")
#print(f"Selected column is column \033[1m{limit+1}\033[0m: \033[1m{selected_column}\033[0m")

#2 option
my_array = np.array([[np.random.randint(0, 50) for x in range(6)] for y in range(5)])


def index_calc(my_array):
    max_value = np.max(my_array)
    index = np.argwhere(my_array == max_value).tolist()

    return index

def limit_calc(index):
    limit = []
    for i in range (len(index)):
        if index[i][1] not in limit:
            limit.append(index[i][1])
    return limit

def selected_column_calc(my_array):
    result = ''
    index = index_calc(my_array)
    limit = limit_calc(index)    
    for i in range (len(limit)):
        selected_column = (my_array[:, limit[i]])
        print(f"Selected column is column \033[1m{limit[i]+1}\033[0m: \033[1m{selected_column}\033[0m")
    
    print(f"Total {len(limit)} column(s)")
   
    
print('Shape: ',my_array.shape)
print(f"\033[1m{my_array}\033[0m")
print(selected_column_calc(my_array))


Shape:  (5, 6)
[[29 11 29 28 38 11]
 [ 7  0 44 27 17 22]
 [31 39 44 23  4 37]
 [11  8  0 49 33  1]
 [10 10 36 16 13 49]]
Selected column is column 4: [28 27 23 49 16]
Selected column is column 6: [11 22 37  1 49]
Total 2 column(s)
None


Напишите функцию, которая принимает на вохд матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [298]:
def get_unique_rows(X):
    X_unique = []
    for i in range(0, len(X)):
        line = list(X[i])
        if line not in X_unique:
            X_unique.append(line)
 
    
    X_unique = np.array(X_unique)

    return X_unique

In [299]:
X = np.random.randint(4, 6, size=(10,3))
print(X)



[[5 5 4]
 [5 5 4]
 [4 5 4]
 [5 5 4]
 [4 4 4]
 [5 5 4]
 [5 4 5]
 [5 4 5]
 [4 5 5]
 [4 5 5]]


In [300]:
get_unique_rows(X)

array([[5, 5, 4],
       [4, 5, 4],
       [4, 4, 4],
       [5, 4, 5],
       [4, 5, 5]])